WebTennisFieldReservation/Controllers/CourtAvailabilityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebTennisFieldReservation.Data;
using WebTennisFieldReservation.Models.Administration;
using WebTennisFieldReservation.Models.CourtAvailability;
using WebTennisFieldReservation.Constants.Names;
using WebTennisFieldReservation.Services.SingleUserMailSender;
using Microsoft.AspNetCore.Antiforgery;

namespace WebTennisFieldReservation.Controllers
{
	[Route("/courtavailability")]	
	public class CourtAvailabilityController : Controller
	{		

		[HttpGet("view")]
		public new IActionResult View()
		{
			var pageData = new AvailabilityPageModel() { Today = DateTime.Now, CheckoutToken = Guid.NewGuid() };
			return View(pageData);
		}
	}
}

WebTennisFieldReservation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebTennisFieldReservation.Models;
using WebTennisFieldReservation.Constants.Names;

namespace WebTennisFieldReservation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Forbidden()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebTennisFieldReservation/Views/Home/Forbidden.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <h2 class="text-danger">403 - FORBIDDEN</h2>
</div>

WebTennisFieldReservation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-start">    
    <p>Click <a asp-controller="CourtAvailability" asp-action="View">here</a> to check court availability</p>
</div>